flowchart LR
    Client[Navegador o Client Terminal] -->|HTTP JSON / Socket JSON| API[Servidor Python - Flask / FastAPI / Socket Server]
    API -->|Llamadas a| DAO[Data Access Object (DAO)]
    DAO -->|Consultas SQL| BBDD[Base de Datos My
